### ISSUE TITLE
1030.ips: The Health status of cpu1 shows Critical after AC

### ISSUE THREAD

**Issue by lxwinspur** [ibm-openbmc/openbmc#266]
The following are the test steps
1. Update BMC Fw or do a factory reset
2. AC and Host **does not** power on
3. check the health status of cpu1 via GUI

Through the event log, we can see that the VPD ecc verification of cpu1 failed
error message: `A VPD ecc exception occurred`
[issues.tar.gz](https://github.com/ibm-openbmc/openbmc/files/10741076/issues.tar.gz)

![image](https://user-images.githubusercontent.com/45955763/218978436-609e834c-1f4e-47e0-9ede-066ec2214690.png)

![image](https://user-images.githubusercontent.com/45955763/218978522-93206f79-bf6c-4688-9e9c-b3ff6ac3cc84.png)

**Comment by jinuthomas** [comment]
The error is due to corrupted vpd on the FRU's mentioned in the error log, In IBM we normally ask GSI team to reflash the correct vpd on the eeprom of the FRU. I am not sure of what process is followed by IPS.
