### ISSUE TITLE
1030.ips: The Status of cpu shows Absent after AC

### ISSUE THREAD

**Issue by lxwinspur** [ibm-openbmc/openbmc#269]
We have 3 Rainier machines that occasionally after AC the CPU `Health status` is OK, but the `Presence status` is Absent.
After redoing the AC, the problem returned.

Dump Log:
[BMC_Dump_Entry.tar.gz](https://github.com/ibm-openbmc/openbmc/files/10782990/BMC_Dump_Entry.tar.gz)

![image](https://user-images.githubusercontent.com/45955763/220069704-1d377011-29b1-4c7c-95ed-b8e03e5fc294.png)

![image](https://user-images.githubusercontent.com/45955763/220537751-d7c09e3f-3e4e-4012-aed2-a21480fdc87a.png)

**Comment by lxwinspur** [comment]
@mzipse @jinuthomas @geissonator 
Please take a look at this issue, thanks!

**Comment by ravindra-srikanth** [comment]
We already have SW552054 to track this issue reported by IPS. As it needs design change to handle this scenario our current target is 1050.

**Comment by mzipse** [comment]
Based on the status for SW552054, this defect is fixed and should be in the 1030.30 service pack.  It will also be in the 1040.10 when it is delivered and then 1050 as well.

**Comment by lxwinspur** [comment]
Thanks @mzipse 
We'll do another round of testing, and if everything works fine, I'll close this issue.

**Comment by lxwinspur** [comment]
@mzipse 
Our test team reported that everything was fine, and will close this issue, Thanks again :)
