### ISSUE TITLE
SBE dump parse fail

### ISSUE THREAD

**Issue by lili-lilili** [ibm-openbmc/openbmc#279]
I tried to parse SBE trace from sbe dump, but encountered some problems.
Some error report here:
https://github.com/open-power/sbe/blob/c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbe-debug.py#L178
Is the tool version on github consistent with the one you @skumar8j

Here is the log:
li@Ubuntu-li:~/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug$ ./sbe-debug.py -l trace -t FILE -r System_Dump_Entry_SBE_30000004 -f plat_dump/30000004.0_0_SbeData_p10_p10_pibmem_dump

Symbol File: [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbe_DD1.syms]
Parsing the Dump header
Missing section indicator is 0x0
BMC System: 1
Running command [hexdump -v -e '1/8 "%016x"' -e '"\n"' plat_dump/30000004.0_0_SbeData_p10_p10_pibmem_dump| xxd -r -p > output_file]
hexdump: x: bad byte count
Running command [cp output_file plat_dump/30000004.0_0_SbeData_p10_p10_pibmem_dump]

Trace buffer symbol addr: [fffd2e80] Trace Buffer Length: [00000838]

String File: [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbeStringFile_DD1]
Running command [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/ppe2fsp /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/DumpPIBMEM /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin ]
Failed converting ppe trace to fsp trace. rc = 6
PPE trace buffer must be version 2.
ERROR running command: 1536

fsp-trace: [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/fsp-trace]
Running command [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/fsp-trace -s /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbeStringFile_DD1 /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin > /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbe_0_0_tracMERG]
fsp-trace.c is_smartDump [503]: read 40 bytes of /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin = 0, 19: No such device
fsp-trace.c parse_opt: file /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin: not an fsp-trace file (Incorrect Version?)
adal_parse.c trace_adal_read_stringfile: stringfile magic cookie not found or corrupted.
fsp-trace.c read_stringfiles: cannot read stringfile '/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbeStringFile_DD1'
ERROR running command: 512
Running command [mv /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/DumpPIBMEM /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/dumpPibMem_trace]

**Comment by lili-lilili** [comment]
Here for more information
https://github.com/ibm-openbmc/openbmc/issues/263

**Comment by lili-lilili** [comment]
@skumar8j  
Please help confirm if the tool in the open source community is a working version?
https://github.com/open-power/sbe/blob/release-fw1030/src/tools/debug/sbe-debug.py

**Comment by lili-lilili** [comment]
I have tried with "-l trace" and "-l forced-trace".
With out modify the tool (sbe-debug.py), all of them will return same error.
Also i confirm that: the firmware create the SBE dump file and the symbol file used to prase the dump file are come from the same source code.

Here is the error log of “-l trace”:
```
$ ./sbe-debug.py -i MSBE -t FILE -l trace -r System_Dump_Entry_SBE_30000001 -f plat_dump/30000001.0_0_SbeData_p10_p10_pibmem_dump 

 Symbol File: [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbe_measurement_seeprom.syms]
Parsing the Dump header
Missing section indicator is 0x0
BMC System: 1
Running command [hexdump -v -e '1/8 "%016x"' -e '"\n"' plat_dump/30000001.0_0_SbeData_p10_p10_pibmem_dump| xxd -r -p > output_file]
hexdump: x: bad byte count
Running command [cp output_file plat_dump/30000001.0_0_SbeData_p10_p10_pibmem_dump]

 Trace buffer symbol addr: [fff86990] Trace Buffer Length: [00001038]

 String File: [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbeMeasurementStringFile]
Running command [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/ppe2fsp /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/DumpPIBMEM /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin ]
Failed converting ppe trace to fsp trace. rc = 6
PPE trace buffer must be version 2.
ERROR running command: 1536 

 fsp-trace: [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/fsp-trace]
Running command [/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/fsp-trace -s /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbeMeasurementStringFile /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin > /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbe_measurement_seeprom_0_tracMERG]
fsp-trace.c is_smartDump [503]: read 40 bytes of /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin = 0, 19: No such device
fsp-trace.c parse_opt: file /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin: not an fsp-trace file (Incorrect Version?)
fsp-trace.c main: failed to parse all files (skipped 1 files)
ERROR running command: 5632 
Running command [mv /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/DumpPIBMEM /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/dumpPibMem_trace]
```

Let check the error "Failed converting ppe trace to fsp trace. rc = 6".

It report by ppe2fsp:
```
/home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/ppe2fsp 
    /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/DumpPIBMEM 
    /home/li/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug/sbetrace.bin
```

I guess DumpPIBMEM is a input file, it will be copy to dumpPibMem_trace at last, please note that dumpPibMem_trace file size is zero.

I think this is cuased by the following error.
```
Running command [hexdump -v -e '1/8 "%016x"' -e '"\n"' plat_dump/30000001.0_0_SbeData_p10_p10_pibmem_dump| xxd -r -p > output_file]
hexdump: x: bad byte count
```

```
li@Ubuntu-li:~/works/P10/fw1030-master/output/build/sbe-p10-c74232131c91c41b418e711f6fc181ff3b881d7a/src/tools/debug$ ll
total 1872
drwxr-xr-x  4 li li   4096 4月  14 14:24 ./
drwxr-xr-x 12 li li   4096 11月 24 21:02 ../
-rw-rw-r--  1 li li      0 4月  14 14:24 dumpPibMem_trace
-rw-r--r--  1 li li   4192 11月 24 21:02 extractMpiplDump.py
-rwxr-xr-x  1 li li 338480 4月  12 14:09 fsp-trace*
-rwxr-xr-x  1 li li  24576 11月 24 21:02 hbbl.bin*
-rw-r--r--  1 li li    202 1月   1  1970 info.yaml
-rw-rw-r--  1 li li  20857 4月  14 14:24 output.binary
-rw-rw-r--  1 li li      0 4月  14 14:24 output_file
drwxrwxr-x  2 li li   4096 4月  14 14:24 plat_dump/
-rwxr-xr-x  1 li li  28312 4月  12 14:08 ppe2fsp*
-rwxr-xr-x  1 li li 638944 4月  12 14:09 ppetracepp*
-rw-r--r--  1 li li 141556 4月  12 14:07 sbe_DD1.syms
-rwxrwxr-x  1 li li  36865 4月  12 14:39 sbe-debug-m.py*
-rwxr-xr-x  1 li li  34928 11月 24 21:02 sbe-debug.py*
-rw-rw-r--  1 li li      0 4月  14 14:24 sbe_measurement_seeprom_0_tracMERG
-rw-r--r--  1 li li  21376 4月  12 14:08 sbe_measurement_seeprom.syms
-rw-r--r--  1 li li 165937 4月  12 14:08 sbeMeasurementStringFile
-rwxr-xr-x  1 li li   7574 11月 24 21:02 sbeModifyPGvalue.py*
-rw-rw-r--  1 li li 157377 4月  12 14:08 sbeStringFile_DD1
-rw-rw-r--  1 li li      0 4月  14 14:24 sbetrace.bin
-rw-rw-r--  1 li li 171314 4月  12 14:08 sbeVerificationStringFile
-rw-r--r--  1 li li  20866 4月  12 14:07 sbe_verification.syms
drwxr-xr-x  2 li li   4096 11月 24 21:02 simics/
-rwxr-xr-x  1 li li  14182 11月 24 21:02 simics-debug-framework.py*
-rwxr-xr-x  1 li li  10540 11月 24 21:02 simics-debug-framework_rainier.py*
-rw-r--r--  1 li li  22089 4月  12 14:37 System_Dump_Entry_SBE_30000001
```

**Comment by skumar8j** [comment]
Do you know which measurement version you were running?
There are two measurement version 2.13 and 2.14

You can use Cronus to query the measurement version. And once again verify if the symbol file used to parse the SBE dump is correct one.
