### ISSUE TITLE
1030-ips: dev ACF can't initiate dump

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#281]
We are unable to initiate dump using the dev acf file, and the web prompts a  "Invalid password"

## Expected Behavior
Successfully 'Initiate dump' using the generated dev acf file.

## Actual Behavior
The  dev acf file can be used to login to ASMI, but when we click "Initiate dump" button, we get a "Invalid password" error.
And we will see a pldm error:
Apr 18 11:11:19 p10bmc pldmd[696]: fileAckWithMetaData with token: 4294967295 and status: 1(AcfFileInvalid) 

## Steps to Reproduce the Problem
1.	We followed this step to create and setup the ACF file: https://github.com/ibm-openbmc/ibm-acf/tree/1030.ips#how-to-setup-this-feature
2.	Login as service account to eBMC GUI
3.	Navigate to Logs ->Dumps
4.	Select "Resource Dump" dump type
5.	Enter "serialctl -hyp -assign" as the resource selector and enter the ACF Password into the "Password" field and select "Initiate dump" to enable the PHYP console.
6.	Error occurred: "Error initiating dump.Invalid password"

![123](https://user-images.githubusercontent.com/26787008/232705086-8993c5dd-67d7-4e05-8ccc-015a14c44921.jpg)

**Comment by ChicagoDuan** [comment]
@manojkiraneda  We saw a pldm error,:
`Apr 18 11:11:19 p10bmc pldmd[696]: fileAckWithMetaData with token: 4294967295 and status: 1(AcfFileInvalid)`
Can you give us some help with this error?  Thanks

**Comment by mzipse** [comment]
Nevermind.  Just saw your steps.  Looks like you have field mode disabled.  Still investigating.

**Comment by ChicagoDuan** [comment]
Hi @mzipse , with the help of YangMing and the IBM team, we have resolved this issue. Thank you
