### ISSUE TITLE
Journal persistence not enabled for Mihawk or Mowgli

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/openbmc#287]
Most IBM servers enable journal persistence via a config override out in https://github.com/ibm-openbmc/openbmc/blob/OP940/meta-ibm/meta-witherspoon/recipes-core/systemd/systemd_%25.bbappend, by bringing in https://github.com/ibm-openbmc/openbmc/blob/OP940/meta-ibm/meta-witherspoon/recipes-core/systemd/systemd/journald-storage-policy.conf.

It doesn't look like Mihawk or Mowgli do this. Any particular reason? The persistent journal has been very useful for debugging failures.

**Comment by mzipse** [comment]
@geissonator , can this be closed now?

**Comment by geissonator** [comment]
Yep, looks good.
