### ISSUE TITLE
1030.20.ips: incorrect description of error message 

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#288]
When a readonly user attempts to modify the permission to Administrator, a message error is displayed. Currently, the error  message is "Error Cannot read property '0' of undefined", which should show  "No permission to modify this setting" or cancel the Administrator permission modification menu for readonly users, only retaining the password modification function.

![user](https://github.com/ibm-openbmc/openbmc/assets/26787008/14fb5fe9-1e75-4493-b910-ac4bb7593f4d)

**Comment by ChicagoDuan** [comment]
@mzipse Can you give us some help with this issue? Thanks.

**Comment by mzipse** [comment]
@Nikhil-Ashoka , can you please take a look at this?  Thanks!

**Comment by mzipse** [comment]
Fix is part of the FW1050.00 release.

**Comment by ChicagoDuan** [comment]
Thanks！After testing, this issue has been fixed on the FW1050 beta version, and I will close this issue when the FW1050 standard version is released.

**Comment by mzipse** [comment]
Fix has been delivered as part of FW1050.  Closing this.
