### ISSUE TITLE
1030.20.ips: Everest: The character display on the SMS web page is disordered when starting in non HMC mode

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#289]
The character display on the SMS web page is disordered when starting in non HMC mode, and the partition is displayed normally when starting in HMC mode
![SMS字符混乱](https://github.com/ibm-openbmc/openbmc/assets/26787008/1438b8a7-da6a-4daa-aa7a-7e183c8f0171)

**Comment by ChicagoDuan** [comment]
@mzipse Can you give us some help with this issue? Thanks.

**Comment by mzipse** [comment]
I have passed this on to the Partition Firmware team a week or two back.  Waiting for a response from them.

**Comment by mzipse** [comment]
We understand root cause now.  The plan is to fix in FW1050 and also backport to earlier releases as well.

**Comment by mzipse** [comment]
Joan R working PHYP change to mimic the same functionality that matches the FSP.  Fix will be in 1030, 1040 and 1050 drivers.

**Comment by mzipse** [comment]
Fix will be in 1030.40, 1040.10 and 1050.00 releases.

**Comment by ChicagoDuan** [comment]
> Fix will be in 1030.40, 1040.10 and 1050.00 releases.

Thanks！After testing, this issue has been fixed on the FW1050 beta version, and I will close this issue when the FW1050 standard version is released.

**Comment by mzipse** [comment]
Fix delivered in FW1050 and also the Service packs.  Closing this.
