### ISSUE TITLE
1040.00.ips: Unable to power on with host secure boot enabled

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#290]
Enable Host secure boot: FW1030.20 can power on normally, but FW1040.00 cannot power on;
Disable Host secure boot: Both FW1030.20 and FW1040.00 can power on normally without any errors.

@mzipse We suspect that the key for 1040 is incorrect. Please help with this issue.
[FW1040 HOSTBOOT.txt](https://github.com/ibm-openbmc/openbmc/files/11966185/FW1040.HOSTBOOT.txt)

**Comment by ChicagoDuan** [comment]
Update some logs：
[error log.zip](https://github.com/ibm-openbmc/openbmc/files/12034318/error.log.zip)

**Comment by mzipse** [comment]
@ChicagoDuan , please confirm that you are upgrading with the IPS production signed FW1030.20 driver to the IPS production signed FW1040.00 driver, true?

**Comment by mzipse** [comment]
If you are upgrading from a Development signed image, it will not work without going through the transtion key process first.

**Comment by yadlapati** [comment]
Is this still an issue with recent drivers (sent on July13th) ?

**Comment by ChicagoDuan** [comment]
The new 1040.00 has solved this problem
