### ISSUE TITLE
1040.00.ips: Incorrect web prompt 

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#293]
The prompt on the Operations ->Server power operations page is incorrect. 
In manual mode, select normal mode, and the prompt is "Current operating mode Normal.  On save  operating mode  will be set to Manual". It should be "Current operating mode Manual.  On save  operating mode  will be set to Normal"

![手动自动提示错误1](https://github.com/ibm-openbmc/openbmc/assets/26787008/fa8657a7-4e17-4ea6-92ff-de970ddb7430)
![手动自动提示错误2](https://github.com/ibm-openbmc/openbmc/assets/26787008/3a84fd6d-be94-4207-b4d8-5cf45ed1b8e8)

**Comment by mzipse** [comment]
@Nikhil-Ashoka , we should take a look at this text.   However, I am not able to recreate this......when I click Manual, then I see this message, which is correct and when I click normal, then the message goes away, which is also correct.  But in my case, the host is powered off.  From the screen shot above, I see the host is powered up.  So I'm wondering if we're displaying this message incorrectly perhaps based on the state of the Host being powered on?

**Comment by Nikhil-Ashoka** [comment]
Okay, We will look into this issue.

**Comment by mzipse** [comment]
Fix will be available when we release the FW1050.00 Release.

**Comment by ChicagoDuan** [comment]
Thanks！After testing, this issue has been fixed on the FW1050 beta version, and I will close this issue when the FW1050 standard version is released.

**Comment by mzipse** [comment]
Fix delivered in FW1050.  Closing this.
