### ISSUE TITLE
1040.00.ips: The Parent ID displayed for the  CXP card in the NVMe expansion chassis (FC #ESR0) is incorrect

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/openbmc#294]
In BMC Web->PCIe Topology, the Parent IDs displayed for the two CXP cards (with IDs 1408 and 1472) in the NVMe expansion chassis (FC #ESR0) are incorrect. Both are incorrectly shown as 75, whereas they should be 32 and 40, respectively. However, on the HMC side, the Parent IDs displayed in the PCIe Topology are correct.

![id错误](https://github.com/ibm-openbmc/openbmc/assets/26787008/fdeda88d-ce8c-4535-aace-9236af282477)
![id错误2](https://github.com/ibm-openbmc/openbmc/assets/26787008/943ac168-f8dc-4430-b4c0-30b16d9a8743)

**Comment by Nikhil-Ashoka** [comment]
Okay, I will look into this issue.

**Comment by mzipse** [comment]
We are tracking this change to the backend and the GUI using internal defect 558040.  Work still in progress.

**Comment by mzipse** [comment]
Fix is being worked here.... https://github.com/ibm-openbmc/webui-vue/pull/145

**Comment by mzipse** [comment]
Fix will be delivered in FW1050 for this.

**Comment by mzipse** [comment]
Fixed delivered.  Please reopen and provide details if you feel this is not fixed.
